### PR TITLE
Improve theme ✌🏼

### PR DESCRIPTION
**Pull request by 19h47**
Turn setup theme function into a class and lint PHP code with WordPress Coding Standards. 

Also update dependencies, especially `gulp-sass` and `timber`.

### CODE REVIEW

**Comment by Awea** [comment]
@19h47 thanks for the pr :heart: 

Is there any reason to have an extra `Makefile` and `README` inside the theme dir, isn't it simpler to have everything at the root of the starter? What do you think?

**Comment by 19h47** [comment]
@Awea Héhé, you're welcome

My thought was that this files are based on the theme not on the starter itself. The theme has to work by itself.

What do you think about it?

**Comment by Awea** [comment]
They are used for the dev environment so having everything accessible from the root of the repo with the other dev tools seems more understable for me ^^

**Comment by 19h47** [comment]
Yes, I think you right. I updated my PR 👍🏼

**Comment by Awea** [comment]
@19h47 thanks again for the PR :)

**Comment by 19h47** [comment]
@Awea My pleasure 🙂

**Pull request merged**
